.TH "bme280_data" 3 "Version 01" "SD_CardTesting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bme280_data \- bme280 sensor structure which comprises of temperature, pressure and humidity data  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bme280_defs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBpressure\fP"
.br
.ti -1c
.RI "double \fBtemperature\fP"
.br
.ti -1c
.RI "double \fBhumidity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
bme280 sensor structure which comprises of temperature, pressure and humidity data 
.PP
Definition at line \fB393\fP of file \fBbme280_defs\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "double bme280_data::humidity"
Compensated humidity 
.PP
Definition at line \fB402\fP of file \fBbme280_defs\&.h\fP\&.
.SS "double bme280_data::pressure"
Compensated pressure 
.PP
Definition at line \fB396\fP of file \fBbme280_defs\&.h\fP\&.
.SS "double bme280_data::temperature"
Compensated temperature 
.PP
Definition at line \fB399\fP of file \fBbme280_defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SD_CardTesting from the source code\&.
