.TH "bme280_uncomp_data" 3 "Version 01" "SD_CardTesting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bme280_uncomp_data \- bme280 sensor structure which comprises of uncompensated temperature, pressure and humidity data  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bme280_defs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBpressure\fP"
.br
.ti -1c
.RI "uint32_t \fBtemperature\fP"
.br
.ti -1c
.RI "uint32_t \fBhumidity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
bme280 sensor structure which comprises of uncompensated temperature, pressure and humidity data 

BME280_USE_FLOATING_POINT 
.PP
Definition at line \fB422\fP of file \fBbme280_defs\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t bme280_uncomp_data::humidity"
Un-compensated humidity 
.PP
Definition at line \fB431\fP of file \fBbme280_defs\&.h\fP\&.
.SS "uint32_t bme280_uncomp_data::pressure"
Un-compensated pressure 
.PP
Definition at line \fB425\fP of file \fBbme280_defs\&.h\fP\&.
.SS "uint32_t bme280_uncomp_data::temperature"
Un-compensated temperature 
.PP
Definition at line \fB428\fP of file \fBbme280_defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SD_CardTesting from the source code\&.
