.TH "bme280" 3 "Version 01" "SD_CardTesting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bme280 \- BME280
.PP
 \- \fRProduct Overview\fP and \fRSensor API Source Code\fP  

.SH SYNOPSIS
.br
.PP
.SS "Topics"

.in +1c
.ti -1c
.RI "Initialization "
.br
.RI "Initialize the sensor and device structure\&. "
.ti -1c
.RI "Registers "
.br
.RI "Generic API for accessing sensor registers\&. "
.ti -1c
.RI "Sensor Settings "
.br
.RI "Generic API for accessing sensor settings\&. "
.ti -1c
.RI "Sensor Mode "
.br
.RI "Generic API for configuring sensor power mode\&. "
.ti -1c
.RI "System "
.br
.RI "API that performs system-level operations\&. "
.ti -1c
.RI "Sensor Data "
.br
.RI "Data processing of sensor\&. "
.ti -1c
.RI "Sensor Delay "
.br
.RI "Generic API for measuring sensor delay\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fRProduct Overview\fP and \fRSensor API Source Code\fP 


.SH "Author"
.PP 
Generated automatically by Doxygen for SD_CardTesting from the source code\&.
