.TH "bme280_calib_data" 3 "Version 01" "SD_CardTesting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bme280_calib_data \- Calibration data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bme280_defs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBdig_t1\fP"
.br
.ti -1c
.RI "int16_t \fBdig_t2\fP"
.br
.ti -1c
.RI "int16_t \fBdig_t3\fP"
.br
.ti -1c
.RI "uint16_t \fBdig_p1\fP"
.br
.ti -1c
.RI "int16_t \fBdig_p2\fP"
.br
.ti -1c
.RI "int16_t \fBdig_p3\fP"
.br
.ti -1c
.RI "int16_t \fBdig_p4\fP"
.br
.ti -1c
.RI "int16_t \fBdig_p5\fP"
.br
.ti -1c
.RI "int16_t \fBdig_p6\fP"
.br
.ti -1c
.RI "int16_t \fBdig_p7\fP"
.br
.ti -1c
.RI "int16_t \fBdig_p8\fP"
.br
.ti -1c
.RI "int16_t \fBdig_p9\fP"
.br
.ti -1c
.RI "uint8_t \fBdig_h1\fP"
.br
.ti -1c
.RI "int16_t \fBdig_h2\fP"
.br
.ti -1c
.RI "uint8_t \fBdig_h3\fP"
.br
.ti -1c
.RI "int16_t \fBdig_h4\fP"
.br
.ti -1c
.RI "int16_t \fBdig_h5\fP"
.br
.ti -1c
.RI "int8_t \fBdig_h6\fP"
.br
.ti -1c
.RI "int32_t \fBt_fine\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Calibration data\&. 
.PP
Definition at line \fB328\fP of file \fBbme280_defs\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t bme280_calib_data::dig_h1"
Calibration coefficient for the humidity sensor 
.PP
Definition at line \fB367\fP of file \fBbme280_defs\&.h\fP\&.
.SS "int16_t bme280_calib_data::dig_h2"
Calibration coefficient for the humidity sensor 
.PP
Definition at line \fB370\fP of file \fBbme280_defs\&.h\fP\&.
.SS "uint8_t bme280_calib_data::dig_h3"
Calibration coefficient for the humidity sensor 
.PP
Definition at line \fB373\fP of file \fBbme280_defs\&.h\fP\&.
.SS "int16_t bme280_calib_data::dig_h4"
Calibration coefficient for the humidity sensor 
.PP
Definition at line \fB376\fP of file \fBbme280_defs\&.h\fP\&.
.SS "int16_t bme280_calib_data::dig_h5"
Calibration coefficient for the humidity sensor 
.PP
Definition at line \fB379\fP of file \fBbme280_defs\&.h\fP\&.
.SS "int8_t bme280_calib_data::dig_h6"
Calibration coefficient for the humidity sensor 
.PP
Definition at line \fB382\fP of file \fBbme280_defs\&.h\fP\&.
.SS "uint16_t bme280_calib_data::dig_p1"
Calibration coefficient for the pressure sensor 
.PP
Definition at line \fB340\fP of file \fBbme280_defs\&.h\fP\&.
.SS "int16_t bme280_calib_data::dig_p2"
Calibration coefficient for the pressure sensor 
.PP
Definition at line \fB343\fP of file \fBbme280_defs\&.h\fP\&.
.SS "int16_t bme280_calib_data::dig_p3"
Calibration coefficient for the pressure sensor 
.PP
Definition at line \fB346\fP of file \fBbme280_defs\&.h\fP\&.
.SS "int16_t bme280_calib_data::dig_p4"
Calibration coefficient for the pressure sensor 
.PP
Definition at line \fB349\fP of file \fBbme280_defs\&.h\fP\&.
.SS "int16_t bme280_calib_data::dig_p5"
Calibration coefficient for the pressure sensor 
.PP
Definition at line \fB352\fP of file \fBbme280_defs\&.h\fP\&.
.SS "int16_t bme280_calib_data::dig_p6"
Calibration coefficient for the pressure sensor 
.PP
Definition at line \fB355\fP of file \fBbme280_defs\&.h\fP\&.
.SS "int16_t bme280_calib_data::dig_p7"
Calibration coefficient for the pressure sensor 
.PP
Definition at line \fB358\fP of file \fBbme280_defs\&.h\fP\&.
.SS "int16_t bme280_calib_data::dig_p8"
Calibration coefficient for the pressure sensor 
.PP
Definition at line \fB361\fP of file \fBbme280_defs\&.h\fP\&.
.SS "int16_t bme280_calib_data::dig_p9"
Calibration coefficient for the pressure sensor 
.PP
Definition at line \fB364\fP of file \fBbme280_defs\&.h\fP\&.
.SS "uint16_t bme280_calib_data::dig_t1"
Calibration coefficient for the temperature sensor 
.PP
Definition at line \fB331\fP of file \fBbme280_defs\&.h\fP\&.
.SS "int16_t bme280_calib_data::dig_t2"
Calibration coefficient for the temperature sensor 
.PP
Definition at line \fB334\fP of file \fBbme280_defs\&.h\fP\&.
.SS "int16_t bme280_calib_data::dig_t3"
Calibration coefficient for the temperature sensor 
.PP
Definition at line \fB337\fP of file \fBbme280_defs\&.h\fP\&.
.SS "int32_t bme280_calib_data::t_fine"
Variable to store the intermediate temperature coefficient 
.PP
Definition at line \fB385\fP of file \fBbme280_defs\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SD_CardTesting from the source code\&.
