.TH "lib Directory Reference" 3 "Version 01" "SD_CardTesting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBbme280\fP"
.br
.ti -1c
.RI "directory \fBFAT32\fP"
.br
.ti -1c
.RI "directory \fBgas_index_algorithm\fP"
.br
.ti -1c
.RI "directory \fBgpio\fP"
.br
.ti -1c
.RI "directory \fBrtc\fP"
.br
.ti -1c
.RI "directory \fBsd\fP"
.br
.ti -1c
.RI "directory \fBsgp41\fP"
.br
.ti -1c
.RI "directory \fBSPI\fP"
.br
.ti -1c
.RI "directory \fBtwi\fP"
.br
.ti -1c
.RI "directory \fBuart\fP"
.br
.in -1c
