.TH "dir_Structure" 3 "Version 01" "SD_CardTesting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dir_Structure
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FAT32\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBname\fP [11]"
.br
.ti -1c
.RI "unsigned char \fBattrib\fP"
.br
.ti -1c
.RI "unsigned char \fBNTreserved\fP"
.br
.ti -1c
.RI "unsigned char \fBtimeTenth\fP"
.br
.ti -1c
.RI "unsigned int \fBcreateTime\fP"
.br
.ti -1c
.RI "unsigned int \fBcreateDate\fP"
.br
.ti -1c
.RI "unsigned int \fBlastAccessDate\fP"
.br
.ti -1c
.RI "unsigned int \fBfirstClusterHI\fP"
.br
.ti -1c
.RI "unsigned int \fBwriteTime\fP"
.br
.ti -1c
.RI "unsigned int \fBwriteDate\fP"
.br
.ti -1c
.RI "unsigned int \fBfirstClusterLO\fP"
.br
.ti -1c
.RI "unsigned long \fBfileSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB81\fP of file \fBFAT32\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char dir_Structure::attrib"

.PP
Definition at line \fB83\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned int dir_Structure::createDate"

.PP
Definition at line \fB87\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned int dir_Structure::createTime"

.PP
Definition at line \fB86\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned long dir_Structure::fileSize"

.PP
Definition at line \fB93\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned int dir_Structure::firstClusterHI"

.PP
Definition at line \fB89\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned int dir_Structure::firstClusterLO"

.PP
Definition at line \fB92\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned int dir_Structure::lastAccessDate"

.PP
Definition at line \fB88\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned char dir_Structure::name[11]"

.PP
Definition at line \fB82\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned char dir_Structure::NTreserved"

.PP
Definition at line \fB84\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned char dir_Structure::timeTenth"

.PP
Definition at line \fB85\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned int dir_Structure::writeDate"

.PP
Definition at line \fB91\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned int dir_Structure::writeTime"

.PP
Definition at line \fB90\fP of file \fBFAT32\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SD_CardTesting from the source code\&.
