.TH "MBRinfo_Structure" 3 "Version 01" "SD_CardTesting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MBRinfo_Structure
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FAT32\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBnothing\fP [446]"
.br
.ti -1c
.RI "unsigned char \fBpartitionData\fP [64]"
.br
.ti -1c
.RI "unsigned int \fBsignature\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBFAT32\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned char MBRinfo_Structure::nothing[446]"

.PP
Definition at line \fB17\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned char MBRinfo_Structure::partitionData[64]"

.PP
Definition at line \fB18\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned int MBRinfo_Structure::signature"

.PP
Definition at line \fB19\fP of file \fBFAT32\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SD_CardTesting from the source code\&.
