.TH "partitionInfo_Structure" 3 "Version 01" "SD_CardTesting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
partitionInfo_Structure
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <FAT32\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBstatus\fP"
.br
.ti -1c
.RI "unsigned char \fBheadStart\fP"
.br
.ti -1c
.RI "unsigned int \fBcylSectStart\fP"
.br
.ti -1c
.RI "unsigned char \fBtype\fP"
.br
.ti -1c
.RI "unsigned char \fBheadEnd\fP"
.br
.ti -1c
.RI "unsigned int \fBcylSectEnd\fP"
.br
.ti -1c
.RI "unsigned long \fBfirstSector\fP"
.br
.ti -1c
.RI "unsigned long \fBsectorsTotal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBFAT32\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned int partitionInfo_Structure::cylSectEnd"

.PP
Definition at line \fB29\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned int partitionInfo_Structure::cylSectStart"

.PP
Definition at line \fB26\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned long partitionInfo_Structure::firstSector"

.PP
Definition at line \fB30\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned char partitionInfo_Structure::headEnd"

.PP
Definition at line \fB28\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned char partitionInfo_Structure::headStart"

.PP
Definition at line \fB25\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned long partitionInfo_Structure::sectorsTotal"

.PP
Definition at line \fB31\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned char partitionInfo_Structure::status"

.PP
Definition at line \fB24\fP of file \fBFAT32\&.h\fP\&.
.SS "unsigned char partitionInfo_Structure::type"

.PP
Definition at line \fB27\fP of file \fBFAT32\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SD_CardTesting from the source code\&.
