.TH "lib/gas_index_algorithm/sensirion_gas_index_algorithm.h" 3 "Version 01" "SD_CardTesting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gas_index_algorithm/sensirion_gas_index_algorithm.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBGasIndexAlgorithmParams\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGASINDEXALGORITHM_H_\fP"
.br
.ti -1c
.RI "#define \fBF16\fP(x)"
.br
.ti -1c
.RI "#define \fBbool\fP   int"
.br
.ti -1c
.RI "#define \fBtrue\fP   1"
.br
.ti -1c
.RI "#define \fBfalse\fP   0"
.br
.ti -1c
.RI "#define \fBLIBRARY_VERSION_NAME\fP   '3\&.2\&.0'"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_ALGORITHM_TYPE_VOC\fP   (0)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_ALGORITHM_TYPE_NOX\fP   (1)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_SAMPLING_INTERVAL\fP   (1\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_INITIAL_BLACKOUT\fP   (45\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_INDEX_GAIN\fP   (230\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_SRAW_STD_INITIAL\fP   (50\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_SRAW_STD_BONUS_VOC\fP   (220\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_SRAW_STD_NOX\fP   (2000\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TAU_MEAN_HOURS\fP   (12\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TAU_VARIANCE_HOURS\fP   (12\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TAU_INITIAL_MEAN_VOC\fP   (20\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TAU_INITIAL_MEAN_NOX\fP   (1200\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_INIT_DURATION_MEAN_VOC\fP   ((3600\&. * 0\&.75))"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_INIT_DURATION_MEAN_NOX\fP   ((3600\&. * 4\&.75))"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_INIT_TRANSITION_MEAN\fP   (0\&.01)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TAU_INITIAL_VARIANCE\fP   (2500\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_INIT_DURATION_VARIANCE_VOC\fP   ((3600\&. * 1\&.45))"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_INIT_DURATION_VARIANCE_NOX\fP   ((3600\&. * 5\&.70))"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_INIT_TRANSITION_VARIANCE\fP   (0\&.01)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_GATING_THRESHOLD_VOC\fP   (340\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_GATING_THRESHOLD_NOX\fP   (30\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_GATING_THRESHOLD_INITIAL\fP   (510\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_GATING_THRESHOLD_TRANSITION\fP   (0\&.09)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_GATING_VOC_MAX_DURATION_MINUTES\fP   ((60\&. * 3\&.))"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_GATING_NOX_MAX_DURATION_MINUTES\fP   ((60\&. * 12\&.))"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_GATING_MAX_RATIO\fP   (0\&.3)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_SIGMOID_L\fP   (500\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_SIGMOID_K_VOC\fP   (\-0\&.0065)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_SIGMOID_X0_VOC\fP   (213\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_SIGMOID_K_NOX\fP   (\-0\&.0101)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_SIGMOID_X0_NOX\fP   (614\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_VOC_INDEX_OFFSET_DEFAULT\fP   (100\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_NOX_INDEX_OFFSET_DEFAULT\fP   (1\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_LP_TAU_FAST\fP   (20\&.0)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_LP_TAU_SLOW\fP   (500\&.0)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_LP_ALPHA\fP   (\-0\&.2)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_VOC_SRAW_MINIMUM\fP   (20000)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_NOX_SRAW_MINIMUM\fP   (10000)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_PERSISTENCE_UPTIME_GAMMA\fP   ((3\&. * 3600\&.))"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TUNING_INDEX_OFFSET_MIN\fP   (1)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TUNING_INDEX_OFFSET_MAX\fP   (250)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TUNING_LEARNING_TIME_OFFSET_HOURS_MIN\fP   (1)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TUNING_LEARNING_TIME_OFFSET_HOURS_MAX\fP   (1000)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TUNING_LEARNING_TIME_GAIN_HOURS_MIN\fP   (1)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TUNING_LEARNING_TIME_GAIN_HOURS_MAX\fP   (1000)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TUNING_GATING_MAX_DURATION_MINUTES_MIN\fP   (0)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TUNING_GATING_MAX_DURATION_MINUTES_MAX\fP   (3000)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TUNING_STD_INITIAL_MIN\fP   (10)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TUNING_STD_INITIAL_MAX\fP   (5000)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TUNING_GAIN_FACTOR_MIN\fP   (1)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_TUNING_GAIN_FACTOR_MAX\fP   (1000)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_MEAN_VARIANCE_ESTIMATOR__GAMMA_SCALING\fP   (64\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_MEAN_VARIANCE_ESTIMATOR__ADDITIONAL_GAMMA_MEAN_SCALING\fP       (8\&.)"
.br
.ti -1c
.RI "#define \fBGasIndexAlgorithm_MEAN_VARIANCE_ESTIMATOR__FIX16_MAX\fP   (32767\&.)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int32_t \fBfix16_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBGasIndexAlgorithm_init\fP (\fBGasIndexAlgorithmParams\fP *params, int32_t algorithm_type)"
.br
.ti -1c
.RI "void \fBGasIndexAlgorithm_reset\fP (\fBGasIndexAlgorithmParams\fP *params)"
.br
.ti -1c
.RI "void \fBGasIndexAlgorithm_get_states\fP (const \fBGasIndexAlgorithmParams\fP *params, int32_t *state0, int32_t *state1)"
.br
.ti -1c
.RI "void \fBGasIndexAlgorithm_set_states\fP (\fBGasIndexAlgorithmParams\fP *params, int32_t state0, int32_t state1)"
.br
.ti -1c
.RI "void \fBGasIndexAlgorithm_set_tuning_parameters\fP (\fBGasIndexAlgorithmParams\fP *params, int32_t index_offset, int32_t learning_time_offset_hours, int32_t learning_time_gain_hours, int32_t gating_max_duration_minutes, int32_t std_initial, int32_t gain_factor)"
.br
.ti -1c
.RI "void \fBGasIndexAlgorithm_get_tuning_parameters\fP (const \fBGasIndexAlgorithmParams\fP *params, int32_t *index_offset, int32_t *learning_time_offset_hours, int32_t *learning_time_gain_hours, int32_t *gating_max_duration_minutes, int32_t *std_initial, int32_t *gain_factor)"
.br
.ti -1c
.RI "void \fBGasIndexAlgorithm_process\fP (\fBGasIndexAlgorithmParams\fP *params, int32_t sraw, int32_t *gas_index)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define bool   int"

.PP
Definition at line \fB56\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define F16( x)"
\fBValue:\fP
.nf
    ((fix16_t)(((x) >= 0) ? ((x)*65536\&.0 + 0\&.5) : ((x)*65536\&.0 \- 0\&.5)))
.PP
.fi

.PP
Definition at line \fB46\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define false   0"

.PP
Definition at line \fB58\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_ALGORITHM_TYPE_NOX   (1)"

.PP
Definition at line \fB71\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_ALGORITHM_TYPE_VOC   (0)"

.PP
Definition at line \fB70\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_GATING_MAX_RATIO   (0\&.3)"

.PP
Definition at line \fB95\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_GATING_NOX_MAX_DURATION_MINUTES   ((60\&. * 12\&.))"

.PP
Definition at line \fB94\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_GATING_THRESHOLD_INITIAL   (510\&.)"

.PP
Definition at line \fB91\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_GATING_THRESHOLD_NOX   (30\&.)"

.PP
Definition at line \fB90\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_GATING_THRESHOLD_TRANSITION   (0\&.09)"

.PP
Definition at line \fB92\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_GATING_THRESHOLD_VOC   (340\&.)"

.PP
Definition at line \fB89\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_GATING_VOC_MAX_DURATION_MINUTES   ((60\&. * 3\&.))"

.PP
Definition at line \fB93\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GASINDEXALGORITHM_H_"

.PP
Definition at line \fB36\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_INDEX_GAIN   (230\&.)"

.PP
Definition at line \fB74\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_INIT_DURATION_MEAN_NOX   ((3600\&. * 4\&.75))"

.PP
Definition at line \fB83\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_INIT_DURATION_MEAN_VOC   ((3600\&. * 0\&.75))"

.PP
Definition at line \fB82\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_INIT_DURATION_VARIANCE_NOX   ((3600\&. * 5\&.70))"

.PP
Definition at line \fB87\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_INIT_DURATION_VARIANCE_VOC   ((3600\&. * 1\&.45))"

.PP
Definition at line \fB86\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_INIT_TRANSITION_MEAN   (0\&.01)"

.PP
Definition at line \fB84\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_INIT_TRANSITION_VARIANCE   (0\&.01)"

.PP
Definition at line \fB88\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_INITIAL_BLACKOUT   (45\&.)"

.PP
Definition at line \fB73\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_LP_ALPHA   (\-0\&.2)"

.PP
Definition at line \fB105\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_LP_TAU_FAST   (20\&.0)"

.PP
Definition at line \fB103\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_LP_TAU_SLOW   (500\&.0)"

.PP
Definition at line \fB104\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_MEAN_VARIANCE_ESTIMATOR__ADDITIONAL_GAMMA_MEAN_SCALING       (8\&.)"

.PP
Definition at line \fB122\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_MEAN_VARIANCE_ESTIMATOR__FIX16_MAX   (32767\&.)"

.PP
Definition at line \fB124\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_MEAN_VARIANCE_ESTIMATOR__GAMMA_SCALING   (64\&.)"

.PP
Definition at line \fB121\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_NOX_INDEX_OFFSET_DEFAULT   (1\&.)"

.PP
Definition at line \fB102\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_NOX_SRAW_MINIMUM   (10000)"

.PP
Definition at line \fB107\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_PERSISTENCE_UPTIME_GAMMA   ((3\&. * 3600\&.))"

.PP
Definition at line \fB108\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_SAMPLING_INTERVAL   (1\&.)"

.PP
Definition at line \fB72\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_SIGMOID_K_NOX   (\-0\&.0101)"

.PP
Definition at line \fB99\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_SIGMOID_K_VOC   (\-0\&.0065)"

.PP
Definition at line \fB97\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_SIGMOID_L   (500\&.)"

.PP
Definition at line \fB96\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_SIGMOID_X0_NOX   (614\&.)"

.PP
Definition at line \fB100\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_SIGMOID_X0_VOC   (213\&.)"

.PP
Definition at line \fB98\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_SRAW_STD_BONUS_VOC   (220\&.)"

.PP
Definition at line \fB76\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_SRAW_STD_INITIAL   (50\&.)"

.PP
Definition at line \fB75\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_SRAW_STD_NOX   (2000\&.)"

.PP
Definition at line \fB77\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TAU_INITIAL_MEAN_NOX   (1200\&.)"

.PP
Definition at line \fB81\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TAU_INITIAL_MEAN_VOC   (20\&.)"

.PP
Definition at line \fB80\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TAU_INITIAL_VARIANCE   (2500\&.)"

.PP
Definition at line \fB85\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TAU_MEAN_HOURS   (12\&.)"

.PP
Definition at line \fB78\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TAU_VARIANCE_HOURS   (12\&.)"

.PP
Definition at line \fB79\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TUNING_GAIN_FACTOR_MAX   (1000)"

.PP
Definition at line \fB120\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TUNING_GAIN_FACTOR_MIN   (1)"

.PP
Definition at line \fB119\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TUNING_GATING_MAX_DURATION_MINUTES_MAX   (3000)"

.PP
Definition at line \fB116\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TUNING_GATING_MAX_DURATION_MINUTES_MIN   (0)"

.PP
Definition at line \fB115\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TUNING_INDEX_OFFSET_MAX   (250)"

.PP
Definition at line \fB110\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TUNING_INDEX_OFFSET_MIN   (1)"

.PP
Definition at line \fB109\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TUNING_LEARNING_TIME_GAIN_HOURS_MAX   (1000)"

.PP
Definition at line \fB114\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TUNING_LEARNING_TIME_GAIN_HOURS_MIN   (1)"

.PP
Definition at line \fB113\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TUNING_LEARNING_TIME_OFFSET_HOURS_MAX   (1000)"

.PP
Definition at line \fB112\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TUNING_LEARNING_TIME_OFFSET_HOURS_MIN   (1)"

.PP
Definition at line \fB111\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TUNING_STD_INITIAL_MAX   (5000)"

.PP
Definition at line \fB118\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_TUNING_STD_INITIAL_MIN   (10)"

.PP
Definition at line \fB117\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_VOC_INDEX_OFFSET_DEFAULT   (100\&.)"

.PP
Definition at line \fB101\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define GasIndexAlgorithm_VOC_SRAW_MINIMUM   (20000)"

.PP
Definition at line \fB106\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define LIBRARY_VERSION_NAME   '3\&.2\&.0'"

.PP
Definition at line \fB67\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SS "#define true   1"

.PP
Definition at line \fB57\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef int32_t \fBfix16_t\fP"

.PP
Definition at line \fB44\fP of file \fBsensirion_gas_index_algorithm\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void GasIndexAlgorithm_get_states (const \fBGasIndexAlgorithmParams\fP * params, int32_t * state0, int32_t * state1)"
Get current algorithm states\&. Retrieved values can be used in \fBGasIndexAlgorithm_set_states()\fP to resume operation after a short interruption, skipping initial learning phase\&. NOTE: This feature can only be used for VOC algorithm type and after at least 3 hours of continuous operation\&. 
.PP
\fBParameters\fP
.RS 4
\fIparams\fP Pointer to the \fBGasIndexAlgorithmParams\fP struct 
.br
\fIstate0\fP State0 to be stored 
.br
\fIstate1\fP State1 to be stored 
.RE
.PP

.PP
Definition at line \fB380\fP of file \fBsensirion_gas_index_algorithm\&.c\fP\&.
.SS "void GasIndexAlgorithm_get_tuning_parameters (const \fBGasIndexAlgorithmParams\fP * params, int32_t * index_offset, int32_t * learning_time_offset_hours, int32_t * learning_time_gain_hours, int32_t * gating_max_duration_minutes, int32_t * std_initial, int32_t * gain_factor)"
Get current parameters to customize the gas index algorithm\&. Refer to \fBGasIndexAlgorithm_set_tuning_parameters()\fP for description of the parameters\&. 
.PP
Definition at line \fB416\fP of file \fBsensirion_gas_index_algorithm\&.c\fP\&.
.SS "void GasIndexAlgorithm_init (\fBGasIndexAlgorithmParams\fP * params, int32_t algorithm_type)"
Initialize the gas index algorithm parameters for the specified algorithm type and reset its internal states\&. Call this once at the beginning\&. 
.PP
\fBParameters\fP
.RS 4
\fIparams\fP Pointer to the \fBGasIndexAlgorithmParams\fP struct 
.br
\fIalgorithm_type\fP 0 (GasIndexAlgorithm_ALGORITHM_TYPE_VOC) for VOC or 1 (GasIndexAlgorithm_ALGORITHM_TYPE_NOX) for NOx 
.RE
.PP

.PP
Definition at line \fB321\fP of file \fBsensirion_gas_index_algorithm\&.c\fP\&.
.SS "void GasIndexAlgorithm_process (\fBGasIndexAlgorithmParams\fP * params, int32_t sraw, int32_t * gas_index)"
Calculate the gas index value from the raw sensor value\&.

.PP
\fBParameters\fP
.RS 4
\fIparams\fP Pointer to the \fBGasIndexAlgorithmParams\fP struct 
.br
\fIsraw\fP Raw value from the SGP4x sensor 
.br
\fIgas_index\fP Calculated gas index value from the raw sensor value\&. Zero during initial blackout period and 1\&.\&.500 afterwards 
.RE
.PP

.PP
Definition at line \fB433\fP of file \fBsensirion_gas_index_algorithm\&.c\fP\&.
.SS "void GasIndexAlgorithm_reset (\fBGasIndexAlgorithmParams\fP * params)"
Reset the internal states of the gas index algorithm\&. Previously set tuning parameters are preserved\&. Call this when resuming operation after a measurement interruption\&. 
.PP
\fBParameters\fP
.RS 4
\fIparams\fP Pointer to the \fBGasIndexAlgorithmParams\fP struct 
.RE
.PP

.PP
Definition at line \fB353\fP of file \fBsensirion_gas_index_algorithm\&.c\fP\&.
.SS "void GasIndexAlgorithm_set_states (\fBGasIndexAlgorithmParams\fP * params, int32_t state0, int32_t state1)"
Set previously retrieved algorithm states to resume operation after a short interruption, skipping initial learning phase\&. This feature should not be used after interruptions of more than 10 minutes\&. Call this once after \fBGasIndexAlgorithm_init()\fP or \fBGasIndexAlgorithm_reset()\fP and the optional \fBGasIndexAlgorithm_set_tuning_parameters()\fP, if desired\&. Otherwise, the algorithm will start with initial learning phase\&. NOTE: This feature can only be used for VOC algorithm type\&. 
.PP
\fBParameters\fP
.RS 4
\fIparams\fP Pointer to the \fBGasIndexAlgorithmParams\fP struct 
.br
\fIstate0\fP State0 to be restored 
.br
\fIstate1\fP State1 to be restored 
.RE
.PP

.PP
Definition at line \fB388\fP of file \fBsensirion_gas_index_algorithm\&.c\fP\&.
.SS "void GasIndexAlgorithm_set_tuning_parameters (\fBGasIndexAlgorithmParams\fP * params, int32_t index_offset, int32_t learning_time_offset_hours, int32_t learning_time_gain_hours, int32_t gating_max_duration_minutes, int32_t std_initial, int32_t gain_factor)"
Set parameters to customize the gas index algorithm\&. Call this once after \fBGasIndexAlgorithm_init()\fP and before optional \fBGasIndexAlgorithm_set_states()\fP, if desired\&. Otherwise, the default values will be used\&.

.PP
\fBParameters\fP
.RS 4
\fIparams\fP Pointer to the \fBGasIndexAlgorithmParams\fP struct 
.br
\fIindex_offset\fP Gas index representing typical (average) conditions\&. Range 1\&.\&.250, default 100 for VOC and 1 for NOx 
.br
\fIlearning_time_offset_hours\fP Time constant of long-term estimator for offset\&. Past events will be forgotten after about twice the learning time\&. Range 1\&.\&.1000 [hours], default 12 [hours] 
.br
\fIlearning_time_gain_hours\fP Time constant of long-term estimator for gain\&. Past events will be forgotten after about twice the learning time\&. Range 1\&.\&.1000 [hours], default 12 [hours] NOTE: This value is not relevant for NOx algorithm type 
.br
\fIgating_max_duration_minutes\fP Maximum duration of gating (freeze of estimator during high gas index signal)\&. 0 (no gating) or range 1\&.\&.3000 [minutes], default 180 [minutes] for VOC and 720 [minutes] for NOx 
.br
\fIstd_initial\fP Initial estimate for standard deviation\&. Lower value boosts events during initial learning period, but may result in larger device-to-device variations\&. Range 10\&.\&.5000, default 50 NOTE: This value is not relevant for NOx algorithm type 
.br
\fIgain_factor\fP Factor used to scale applied gain value when calculating gas index\&. Range 1\&.\&.1000, default 230 
.RE
.PP

.PP
Definition at line \fB400\fP of file \fBsensirion_gas_index_algorithm\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SD_CardTesting from the source code\&.
