.TH "lib/SPI/SPI_routines.c" 3 "Version 01" "SD_CardTesting" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/SPI/SPI_routines.c
.SH SYNOPSIS
.br
.PP
\fR#include <avr/io\&.h>\fP
.br
\fR#include 'SPI_routines\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBspi_init\fP (void)"
.br
.ti -1c
.RI "unsigned char \fBSPI_transmit\fP (unsigned char \fBdata\fP)"
.br
.ti -1c
.RI "unsigned char \fBSPI_receive\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void spi_init (void )"

.PP
Definition at line \fB17\fP of file \fBSPI_routines\&.c\fP\&.
.SS "unsigned char SPI_receive (void )"

.PP
Definition at line \fB42\fP of file \fBSPI_routines\&.c\fP\&.
.SS "unsigned char SPI_transmit (unsigned char data)"

.PP
Definition at line \fB29\fP of file \fBSPI_routines\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SD_CardTesting from the source code\&.
