/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * I2C-Generator: 0.3.0
 * Yaml Version: 0.1.0
 * Template Version: 0.7.0-62-g3d691f9
 */
/*
 * Copyright (c) 2021, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */


/* Minimal SGP41 implementation using `twi` library.
 * This implements basic commands used by the main program and
 * performs CRC checks for received data. It avoids Arduino/Wire.
 */


#include "SensirionI2CSgp41.h"
#include <stdint.h>
#include <stddef.h>
#include <util/delay.h>
#include "twi.h"


#define SGP41_I2C_ADDRESS 0x59


/**
 * @brief  Calculate Sensirion CRC-8 over input data.
 * @param  data Pointer to data bytes.
 * @param  count Number of bytes.
 * @return CRC-8 value.
 */
static uint8_t sensirion_crc(const uint8_t *data, size_t count) {
    uint8_t crc = 0xFF;
    for (size_t i = 0; i < count; ++i) {
        crc ^= data[i];
        for (uint8_t bit = 0; bit < 8; ++bit) {
            if (crc & 0x80)
                crc = (uint8_t)((crc << 1) ^ 0x31);
            else
                crc <<= 1;
        }
    }
    return crc;
}


/**
 * @brief  Send SGP41 command and optional data words with CRC.
 * @param  command      16-bit command code.
 * @param  words        Pointer to data words (may be NULL if words_count=0).
 * @param  words_count  Number of 16-bit data words.
 * @return 0 on success, negative value on error.
 */
static int write_command_with_words(uint16_t command, const uint16_t *words,
                                    size_t words_count) {
    twi_start();
    if (twi_write((SGP41_I2C_ADDRESS << 1) | TWI_WRITE)) {
        twi_stop();
        return -1; // address NACK
    }


    /* command high, low */
    uint8_t cmd_hi = (uint8_t)((command >> 8) & 0xFF);
    uint8_t cmd_lo = (uint8_t)(command & 0xFF);
    if (twi_write(cmd_hi)) { twi_stop(); return -2; }
    if (twi_write(cmd_lo)) { twi_stop(); return -3; }


    // send data words with CRC (each word = 2 bytes + 1 crc)
    for (size_t i = 0; i < words_count; ++i) {
        uint8_t b1 = (uint8_t)((words[i] >> 8) & 0xFF);
        uint8_t b2 = (uint8_t)(words[i] & 0xFF);
        if (twi_write(b1)) { twi_stop(); return -4; }
        if (twi_write(b2)) { twi_stop(); return -5; }
        uint8_t crc = sensirion_crc((const uint8_t[]){b1, b2}, 2);
        if (twi_write(crc)) { twi_stop(); return -6; }
    }


    twi_stop();
    return 0;
}


/**
 * @brief  Read bytes from SGP41 via I2C.
 * @param  buf       Pointer to destination buffer.
 * @param  num_bytes Number of bytes to read.
 * @return 0 on success, negative value on error.
 */
static int read_bytes(uint8_t *buf, size_t num_bytes) {
    twi_start();
    if (twi_write((SGP41_I2C_ADDRESS << 1) | TWI_READ)) {
        twi_stop();
        return -1;
    }
    for (size_t i = 0; i < num_bytes; ++i) {
        uint8_t ack = (i + 1 < num_bytes) ? TWI_ACK : TWI_NACK;
        buf[i] = twi_read(ack);
    }
    twi_stop();
    return 0;
}


/**
 * @brief  Verify CRC and extract 16-bit words from [MSB, LSB, CRC] groups.
 * @param  buf       Input buffer containing groups.
 * @param  groups    Number of 3-byte groups.
 * @param  out_words Output array for decoded 16-bit words.
 * @return 0 on success, negative value on CRC error.
 */
static int check_and_extract_words(const uint8_t *buf, size_t groups,
                                   uint16_t *out_words) {
    for (size_t i = 0; i < groups; ++i) {
        uint8_t b1 = buf[i * 3 + 0];
        uint8_t b2 = buf[i * 3 + 1];
        uint8_t crc = buf[i * 3 + 2];
        uint8_t expected = sensirion_crc((const uint8_t[]){b1, b2}, 2);
        if (crc != expected) {
            return -2; // CRC error
        }
        out_words[i] = (uint16_t)((b1 << 8) | b2);
    }
    return 0;
}


/**
 * @brief  Execute SGP41 VOC conditioning measurement.
 * @param  defaultRh Default RH in ticks.
 * @param  defaultT  Default temperature in ticks.
 * @param  srawVoc   Pointer to store VOC raw signal.
 * @return 0 on success, non-zero error code otherwise.
 */
uint16_t sgp41_executeConditioning(uint16_t defaultRh, uint16_t defaultT,
                                   uint16_t* srawVoc) {
    uint16_t cmd = 0x2612;
    uint16_t args[2] = { defaultRh, defaultT };
    if (write_command_with_words(cmd, args, 2) != 0) return 1;
    _delay_ms(50);
    uint8_t buf[3];
    if (read_bytes(buf, 3) != 0) return 2;
    uint16_t out;
    if (check_and_extract_words(buf, 1, &out) != 0) return 3;
    *srawVoc = out;
    return 0;
}


/**
 * @brief  Measure VOC and NOx raw signals with humidity and temperature compensation.
 * @param  relativeHumidity RH in ticks.
 * @param  temperature      Temperature in ticks.
 * @param  srawVoc          Pointer to store VOC raw signal.
 * @param  srawNox          Pointer to store NOx raw signal.
 * @return 0 on success, non-zero error code otherwise.
 */
uint16_t sgp41_measureRawSignals(uint16_t relativeHumidity,
                                 uint16_t temperature, uint16_t* srawVoc,
                                 uint16_t* srawNox) {
    uint16_t cmd = 0x2619;
    uint16_t args[2] = { relativeHumidity, temperature };
    if (write_command_with_words(cmd, args, 2) != 0) return 1;
    _delay_ms(50);
    uint8_t buf[6];
    if (read_bytes(buf, 6) != 0) return 2;
    uint16_t out[2];
    if (check_and_extract_words(buf, 2, out) != 0) return 3;
    *srawVoc = out[0];
    *srawNox = out[1];
    return 0;
}


/**
 * @brief  Run SGP41 on-chip self-test.
 * @param  testResult Pointer to store 16-bit self-test result.
 * @return 0 on success, non-zero error code otherwise.
 */
uint16_t sgp41_executeSelfTest(uint16_t* testResult) {
    uint16_t cmd = 0x280E;
    if (write_command_with_words(cmd, NULL, 0) != 0) return 1;
    _delay_ms(320);
    uint8_t buf[3];
    if (read_bytes(buf, 3) != 0) return 2;
    uint16_t out;
    if (check_and_extract_words(buf, 1, &out) != 0) return 3;
    *testResult = out;
    return 0;
}


/**
 * @brief  Turn off SGP41 heater.
 * @return 0 on success, non-zero error code otherwise.
 */
uint16_t sgp41_turnHeaterOff(void) {
    uint16_t cmd = 0x3615;
    if (write_command_with_words(cmd, NULL, 0) != 0) return 1;
    _delay_ms(1);
    return 0;
}


/**
 * @brief  Read SGP41 serial number (48 bits).
 * @param  serialNumber Array of 3 x 16-bit words to store serial number.
 * @return 0 on success, non-zero error code otherwise.
 */
uint16_t sgp41_getSerialNumber(uint16_t serialNumber[]) {
    uint16_t cmd = 0x3682;
    if (write_command_with_words(cmd, NULL, 0) != 0) return 1;
    _delay_ms(1);
    uint8_t buf[9];
    if (read_bytes(buf, 9) != 0) return 2;
    if (check_and_extract_words(buf, 3, serialNumber) != 0) return 3;
    return 0;
}
