/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * I2C-Generator: 0.3.0
 * Yaml Version: 0.1.0
 * Template Version: 0.7.0-62-g3d691f9
 */
/*
 * Copyright (c) 2021, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */


#ifndef SENSIRIONI2CSGP41_H
#define SENSIRIONI2CSGP41_H
 #include <stdint.h>
// Minimal SGP41 C interface using project's `twi` library (no Arduino/Wire)


#ifdef __cplusplus
extern "C" {
#endif


/**
 * @brief  Send conditioning command and return SRAW_VOC.
 * @param  defaultRh Default humidity in ticks (0x8000 if unknown).
 * @param  defaultT  Default temperature in ticks (0x6666 if unknown).
 * @param  srawVoc   Pointer to store SRAW_VOC output.
 * @return 0 on success, non-zero error code otherwise.
 */
uint16_t sgp41_executeConditioning(uint16_t defaultRh, uint16_t defaultT,
                                   uint16_t* srawVoc);


/**
 * @brief  Measure raw signals (VOC and NOx).
 * @param  relativeHumidity Humidity in ticks.
 * @param  temperature      Temperature in ticks.
 * @param  srawVoc          Pointer to store SRAW_VOC output.
 * @param  srawNox          Pointer to store SRAW_NOX output.
 * @return 0 on success, non-zero error code otherwise.
 */
uint16_t sgp41_measureRawSignals(uint16_t relativeHumidity,
                                 uint16_t temperature, uint16_t* srawVoc,
                                 uint16_t* srawNox);


/**
 * @brief  Execute self-test.
 * @param  testResult Pointer to store test result (0xD400 = OK).
 * @return 0 on success, non-zero error code otherwise.
 */
uint16_t sgp41_executeSelfTest(uint16_t* testResult);


/**
 * @brief  Turn heater off.
 * @return 0 on success, non-zero error code otherwise.
 */
uint16_t sgp41_turnHeaterOff(void);


/**
 * @brief  Get serial number.
 * @param  serialNumber Array of 3 uint16_t to store serial number.
 * @return 0 on success, non-zero error code otherwise.
 */
uint16_t sgp41_getSerialNumber(uint16_t serialNumber[]);


#ifdef __cplusplus
}
#endif


#endif /* SENSIRIONI2CSGP41_H */
